### PR TITLE
Update to README.md

### PR DESCRIPTION
**Pull request by chucksnow**
Added a new note to the README.md file
# Header 1
### Header 3
**Bold Text**
_Italicized Text_

> Quote
`get-git`
[https://www.google.com](url)
[TestText.txt](https://github.com/chucksnow/Hello-World/files/1382591/TestText.txt)

- Bullet List

1. Numbered List

- [ ] Task List
@Chuck-Snow
👍 :
👎 
🔢 
👋 

Let's rename *our-new-project* to *our-old-project*.
Let's rename \*our-new-project\* to \*our-old-project\*.

This is one paragraph. 

This is another paragraph.

### CODE REVIEW

**Comment by Chuck-Snow** [comment]
Just adding a comment to see how the collaboration works. @chucksnow 👍

**Comment by Chuck-Snow** [comment]
[Google](www.google.com)

**Comment by chucksnow** [comment]
Welcome to xFinity
[Welome to xFinity](https://www.xfinity.com)

**Comment by chucksnow** [comment]
[Here is a link to xFinity](https://xfinity.com)

**Comment by Chuck-Snow** [comment]
Another comment to see if chucksnow gets a notification

**Comment by chucksnow** [comment]
yes, chucksnow got the reply.  Will Chuck-Snow get a message without a mention.

**Pull request merged**
